### ISSUE TITLE
Some feed back here

### ISSUE THREAD

**Issue by Mister-Hope** [DreamOfIce/vuepress-plugin-i18n#1]
1. Could you open discussion panel so that I can post things like this correctly?
2. `sourcePath` seems to be the locale path that the original docs locale at, so maybe it should be named something like `baseLocalePath`?
3. I think you should register the component globally, as it's possible to appear in any none `base locale` page, so this component name should be preserved.
4. I think this can help you in many ways: https://shared.vuejs.press/

**Comment by DreamOfIce** [comment]
> 1. Could you open discussion panel so that I can post things like this correctly? 

Discuss panel has been opened.

> I think you should register the component globally, as it's possible to appear in any none base locale page, so this component name should be preserved

I'm not sure I understand you correctly, but I had registered I18nTip component in client config:
https://github.com/DreamOfIce/vuepress-plugin-i18n/blob/77a41ec43cdd0908f980d2ff0db2f4f143f5470e/src/client/config.ts#L6-L8

**Comment by Mister-Hope** [comment]
Then why are you asking to register a component locally in page?

**Comment by DreamOfIce** [comment]
I didn't register it locally, I just used it (add a line "<I18nTip />" before the body)
